[package]
name = "bundle_runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
bencher = "0.1.5"
[profile.release]
lto = true
[[bench]]
name = "jit_vs_native"
harness = false
